apiVersion : apps/v1
kind: Deployment
metadata:
  name: elegant 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elegant
  template:
    metadata:
      labels:
        app: elegant
    spec:
      containers:
        - name: elegant 
          image: elegant.azurecr.io/elegant
          ports:
          - containerPort: 80
