on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Docker build and push to a Azure Container registry (ACR)
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: './sample-app'
        file: ./sample-app/Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/ele:${{ github.sha }}
    
    # Set the target AKS cluster. 
    - uses: azure/k8s-actions/aks-set-context@master
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: elegant
        resource-group: world
    
    # Create imagepullsecret for Azure Container registry (ACR)
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: elegant-secret
        namespace: default
    
    # Deploy app to AKS
    - uses: azure/k8s-actions/k8s-deploy@master
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/ele:${{ github.sha }}
        imagepullsecrets: |
          elegant-secret
        # namespace: <optional>
